services:
  _defaults:
      autowire: true
      autoconfigure: true
      public: false

  OmnideskBundle\Service\:
      resource: '../../Service'
      public: true

  OmnideskBundle\Factory\:
      resource: '../../Factory'

  OmnideskBundle\DataTransformer\:
      resource: '../../DataTransformer'

  OmnideskBundle\Configuration\:
      resource: '../../Configuration'

  OmnideskBundle\Service\RequestService:
      arguments:
          $config: "%omnidesk%"

