services:
  # Services
  guzzle.client:
    class: GuzzleHttp\Client

  service.request:
    class: OmnideskBundle\Service\RequestService
    arguments: ["%omnidesk%", "@guzzle.client"]

  service.cases:
    class: OmnideskBundle\Service\CasesService
    arguments:
      - "@service.request"
      - "@transformer.request.create_cases"
      - "@transformer.request.get_cases"
      - "@transformer.request.view_cases"
      - "@transformer.response.cases"
      - "@transformer.response.get_cases"

  service.message:
    class: OmnideskBundle\Service\MessageService
    arguments:
      - "@service.request"
      - "@transformer.request.get_messages"
      - "@transformer.response.get_messages"

  service.language:
    class: OmnideskBundle\Service\LanguageService
    arguments:
      - "@service.request"
      - "@transformer.response.get_language"

  # Data Transformers
  # Request
  transformer.request.create_cases:
    class: OmnideskBundle\DataTransformer\Request\CreateCasesRequestDataTransformer
  transformer.request.get_cases:
    class: OmnideskBundle\DataTransformer\Request\GetCasesRequestDataTransformer
  transformer.request.view_cases:
    class: OmnideskBundle\DataTransformer\Request\ViewCasesRequestDataTransformer
  transformer.request.get_messages:
    class: OmnideskBundle\DataTransformer\Request\GetMessagesRequestDataTransformer
  # Response
  transformer.response.cases:
    class: OmnideskBundle\DataTransformer\Response\CasesResponseDataTransformer
    arguments: ["@transformer.entity.cases"]
  transformer.response.get_cases:
    class: OmnideskBundle\DataTransformer\Response\GetCasesResponseDataTransformer
    arguments: ["@transformer.entity.cases"]
  transformer.response.get_messages:
    class: OmnideskBundle\DataTransformer\Response\GetMessagesResponseDataTransformer
    arguments: ["@transformer.entity.message"]
  transformer.response.get_language:
    class: OmnideskBundle\DataTransformer\Response\GetLanguageResponseDataTransformer
    arguments: ["@transformer.entity.language"]
  # Entity
  transformer.entity.cases:
    class: OmnideskBundle\DataTransformer\Entity\CasesDataTransformer
  transformer.entity.message:
    class: OmnideskBundle\DataTransformer\Entity\MessageDataTransformer
  transformer.entity.language:
    class: OmnideskBundle\DataTransformer\Entity\LanguageDataTransformer
